### PR TITLE
Lito's fluid simulation

### PR DESCRIPTION
**Pull request by litonico**
[Smoothed Particle Hydrodynamics](https://en.wikipedia.org/wiki/Smoothed-particle_hydrodynamics) fluid simulation!

### CODE REVIEW

**Comment by zenspider** [comment]
`.DS_Store` is proof that `git add -a` is a Bad Thing™.

**Comment by zenspider** [comment]
I can't merge this. You're using code that's not in the PR. `spectrum` is the first.

**Comment by litonico** [comment]
Cleaned up!

**Comment by zenspider** [comment]
mmm... this is done

**Pull request closed without merging**
